
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon May 28 21:32:59 CEST 2018
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GTEQ = 35;
  public static final int LBRACKET = 14;
  public static final int CHAR = 42;
  public static final int CONST = 13;
  public static final int LTEQ = 37;
  public static final int NOTEQUAL = 33;
  public static final int LPAREN = 6;
  public static final int SEMI = 5;
  public static final int CONTINUE = 30;
  public static final int MINUS = 16;
  public static final int RPAREN = 7;
  public static final int AND = 38;
  public static final int LT = 36;
  public static final int OR = 39;
  public static final int COMMA = 8;
  public static final int CLASS = 40;
  public static final int INC = 21;
  public static final int DIV = 18;
  public static final int PLUS = 11;
  public static final int IF = 26;
  public static final int DOT = 31;
  public static final int EOF = 0;
  public static final int RETURN = 10;
  public static final int RBRACKET = 15;
  public static final int EQUAL = 12;
  public static final int TRUE = 43;
  public static final int NEW = 23;
  public static final int error = 1;
  public static final int ISEQUAL = 32;
  public static final int MUL = 17;
  public static final int NUMBER = 41;
  public static final int MOD = 19;
  public static final int IDENT = 45;
  public static final int BREAK = 24;
  public static final int LBRACE = 3;
  public static final int ELSE = 25;
  public static final int READ = 20;
  public static final int WHILE = 28;
  public static final int RBRACE = 4;
  public static final int EXTENDS = 29;
  public static final int PROG = 2;
  public static final int DEC = 22;
  public static final int FALSE = 44;
  public static final int GT = 34;
  public static final int PRINT = 9;
  public static final int DO = 27;
}

